import type { Metadata } from "next";
import Link from "next/link";
import { Arrow, Footer, Header, PageIntro, SectionHeading } from "../components/site-shell";

export const metadata: Metadata = { title: "About", description: "About Usaid Ahmed—AI Engineer, full-stack AI product builder, BSCS student, and Co-Founder of AgentHive in Karachi, Pakistan.", alternates: { canonical: "/about" } };

const capabilityGroups = [
  ["AI systems", "Machine learning, deep learning, NLP, LLMs, RAG, LangChain, LangGraph, TensorFlow, PyTorch"],
  ["Product engineering", "Python, FastAPI, Node.js, React, Next.js, JavaScript, REST APIs, product interfaces"],
  ["Data & infrastructure", "PostgreSQL, MongoDB, ChromaDB, Redis, Pandas, Parquet, GitHub Actions, Docker"],
];

export default function AboutPage() {
  return <><Header /><main><PageIntro eyebrow="About" title="Engineering intelligence from model to product." description="I bring AI, data, backend systems, and product interfaces together to turn ambitious technical ideas into useful, testable experiences." />
    <section className="about-story shell"><div className="about-positioning"><span>AI ENGINEER / CO-FOUNDER</span><h2>Building across the full intelligence-to-interface stack.</h2><p>Karachi, Pakistan<br />Working with global ambition</p></div><div className="about-narrative"><p className="lead">I’m Usaid Ahmed—an AI Engineer, full-stack AI product builder, and Co-Founder of AgentHive.</p><p>I design production-minded intelligent systems across machine learning, generative AI, agentic workflows, RAG, computer vision, predictive pipelines, APIs, and modern web interfaces. My strength is connecting these layers into one coherent product experience.</p><p>My foundation began in MERN development and expanded through a one-year AI & Data Science program at Saylani. At 10Pearls, I contributed to a PM2.5 forecasting pipeline spanning data ingestion, feature preparation, model evaluation, dashboarding, and CI/CD. Today, as an AI Engineering Intern at Saylani, I build full-stack AI applications using FastAPI, React, LangChain, LangGraph, vector retrieval, and LLM integrations.</p><p>As Co-Founder of AgentHive, I’m also learning what it takes to move from a capable AI demo to a trustworthy product—designing around permissions, human approvals, memory, budgets, observability, and real operational workflows.</p><div className="profile-facts"><div><span>Based in</span><strong>Karachi, Pakistan</strong><small>Working globally</small></div><div><span>Building</span><strong>AgentHive</strong><small>Co-Founder</small></div><div><span>Focus</span><strong>End-to-end AI products</strong><small>Intelligence through interface</small></div></div></div></section>
    <section className="now-section shell"><div className="now-heading"><p className="kicker"><span>Now</span></p><h2>The work is active, not archived.</h2><p>A living view of what I am advancing, validating, and explaining right now.</p></div><div className="now-list"><Link href="/work/agenthive"><span>01</span><div><small>Founder build</small><h3>AgentHive</h3><p>Moving a controlled agent proof of concept toward a governed multi-tenant MVP.</p></div><Arrow diagonal /></Link><Link href="/work/neuroglioma-ai"><span>02</span><div><small>Clinical AI research</small><h3>NeuroGlioma AI</h3><p>Advancing calibrated classification, 3D segmentation, quantification, and clinical viewing.</p></div><Arrow diagonal /></Link><Link href="/blog"><span>03</span><div><small>Weekly publishing</small><h3>Field notes</h3><p>Turning engineering decisions, evaluation lessons, and product thinking into useful articles.</p></div><Arrow diagonal /></Link></div></section>
    <section className="principles-section"><div className="shell"><SectionHeading eyebrow="Operating principles" title="How I make technical decisions." /><div className="principles-grid"><article><span>01</span><h3>Start with the decision</h3><p>Understand what the user needs to decide or complete before choosing a model, agent framework, or interface.</p></article><article><span>02</span><h3>Expose uncertainty</h3><p>Design fallbacks, evidence, thresholds, and human escalation instead of hiding uncertainty behind confident language.</p></article><article><span>03</span><h3>Build end to end</h3><p>Connect data, intelligence, APIs, state, controls, and experience early enough to test the real product assumption.</p></article></div></div></section>
    <section className="capability-map shell"><SectionHeading eyebrow="Technical range" title="One product, many connected layers." /><div>{capabilityGroups.map(([title, copy], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="journey-section shell"><SectionHeading eyebrow="Current journey" title="Learning by building real systems." /><div className="timeline"><article><span>2023—24</span><div><h3>MERN Stack Development</h3><p>Built a practical foundation in web interfaces, APIs, backend development, and databases through Expertizo Institute.</p></div></article><article><span>2025</span><div><h3>Data Science Intern · 10Pearls</h3><p>Contributed to a Karachi PM2.5 forecasting pipeline across ingestion, data preparation, models, dashboarding, CI/CD, and feature-store exposure.</p></div></article><article><span>2025—26</span><div><h3>AI & Data Science · Saylani</h3><p>Completed a one-year program spanning machine learning, deep learning, NLP, generative AI, data work, and applied projects.</p></div></article><article><span>2026—Now</span><div><h3>AI Engineering Intern · Saylani</h3><p>Building RAG, agentic, image-classification, and full-stack AI applications with FastAPI, React, LangChain, LangGraph, and model integrations.</p></div></article><article><span>Building</span><div><h3>Co-Founder · AgentHive</h3><p>Developing the product architecture and controlled proof of concept for an enterprise AI workforce platform.</p></div></article></div></section>
    <section className="about-cta shell"><h2>Let’s turn an intelligent idea into a useful product.</h2><Link className="button button-primary" href="/contact">Start a conversation <Arrow /></Link></section>
  </main><Footer /></>;
}
