import type { Metadata } from "next";
import Link from "next/link";
import { Arrow, Footer, Header, PageIntro, PortraitMorph, SectionHeading } from "../components/site-shell";

export const metadata: Metadata = { title: "About", description: "About Usaid Ahmed—AI Engineer, full-stack AI product builder, BSCS student, and Co-Founder of AgentHive in Karachi, Pakistan.", alternates: { canonical: "/about" } };

const capabilityGroups = [
  ["AI systems", "Machine learning, deep learning, NLP, LLMs, RAG, LangChain, LangGraph, TensorFlow, PyTorch"],
  ["Product engineering", "Python, FastAPI, Node.js, React, Next.js, JavaScript, REST APIs, product interfaces"],
  ["Data & infrastructure", "PostgreSQL, MongoDB, ChromaDB, Redis, Pandas, Parquet, GitHub Actions, Docker"],
];

export default function AboutPage() {
  return <><Header /><main><PageIntro eyebrow="About" title="Curious enough to explore. Disciplined enough to engineer." description="I work across AI, data, backend, and product interfaces because useful intelligent systems rarely fit inside one technical layer." />
    <section className="about-story shell"><div className="about-portrait-wrap"><PortraitMorph /><p>Original portrait → AI layer. A small interaction that reflects how I work: human judgment first, intelligent systems around it.</p></div><div className="about-narrative"><p className="lead">I’m Usaid Ahmed—an AI Engineer and product builder studying Computer Science at UBIT, University of Karachi.</p><p>My path started with MERN development and moved deeper into data science, machine learning, generative AI, and agentic systems. That full-stack foundation shapes how I approach AI: not as an isolated model, but as one part of a complete user and business workflow.</p><p>I completed Saylani’s one-year AI & Data Science program, contributed to an AQI forecasting pipeline during a Data Science internship at 10Pearls, and now build full-stack AI applications as an AI Engineering Intern at Saylani.</p><p>I’m also Co-Founder of AgentHive, an early-stage enterprise AI workforce platform. Building it is teaching me to think beyond the happy path—about permissions, approvals, memory, budgets, observability, product strategy, and trust.</p></div></section>
    <section className="principles-section"><div className="shell"><SectionHeading eyebrow="Operating principles" title="How I make technical decisions." /><div className="principles-grid"><article><span>01</span><h3>Start with the decision</h3><p>Understand what the user needs to decide or complete before choosing a model, agent framework, or interface.</p></article><article><span>02</span><h3>Expose uncertainty</h3><p>Design fallbacks, evidence, thresholds, and human escalation instead of hiding uncertainty behind confident language.</p></article><article><span>03</span><h3>Build end to end</h3><p>Connect data, intelligence, APIs, state, controls, and experience early enough to test the real product assumption.</p></article></div></div></section>
    <section className="capability-map shell"><SectionHeading eyebrow="Technical range" title="One product, many connected layers." /><div>{capabilityGroups.map(([title, copy], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="journey-section shell"><SectionHeading eyebrow="Current journey" title="Learning by building real systems." /><div className="timeline"><article><span>2023—24</span><div><h3>MERN Stack Development</h3><p>Built a practical foundation in web interfaces, APIs, backend development, and databases through Expertizo Institute.</p></div></article><article><span>2025</span><div><h3>Data Science Intern · 10Pearls</h3><p>Contributed to a Karachi PM2.5 forecasting pipeline across ingestion, data preparation, models, dashboarding, CI/CD, and feature-store exposure.</p></div></article><article><span>2025—26</span><div><h3>AI & Data Science · Saylani</h3><p>Completed a one-year program spanning machine learning, deep learning, NLP, generative AI, data work, and applied projects.</p></div></article><article><span>2026—Now</span><div><h3>AI Engineering Intern · Saylani</h3><p>Building RAG, agentic, image-classification, and full-stack AI applications with FastAPI, React, LangChain, LangGraph, and model integrations.</p></div></article><article><span>Building</span><div><h3>Co-Founder · AgentHive</h3><p>Developing the product architecture and controlled proof of concept for an enterprise AI workforce platform.</p></div></article></div></section>
    <section className="about-cta shell"><h2>Let’s turn an intelligent idea into a useful product.</h2><Link className="button button-primary" href="/contact">Start a conversation <Arrow /></Link></section>
  </main><Footer /></>;
}
