import Link from "next/link";
import { Arrow, Footer, Header, ProjectVisual, SectionHeading } from "./components/site-shell";
import { caseStudies, engineeringMetrics, insights, services } from "./data/site";

export default function Home() {
  return <><Header /><main>
    <section className="hero shell">
      <div className="hero-copy"><p className="kicker hero-kicker"><span className="status-dot" /> AI engineer · Founder · Product builder</p><h1><span>Intelligence,</span><br />engineered into <em>products.</em></h1><p className="hero-description">I’m Usaid Ahmed. I turn complex AI ideas into usable products—combining machine learning, agentic workflows, RAG, data systems, and full-stack engineering.</p><div className="hero-actions"><Link className="button button-primary" href="/contact">Start a conversation <Arrow /></Link><Link className="button button-ghost" href="/work">Explore selected work <Arrow diagonal /></Link></div></div>
      <div className="hero-system" aria-label="Animated representation of an AI product system"><div className="system-glow" /><div className="system-orbit orbit-one"><i /><i /><i /></div><div className="system-orbit orbit-two"><i /><i /></div><div className="system-core"><span>AI</span><small>PRODUCT<br />SYSTEM</small></div><div className="system-label label-one"><i />MODEL</div><div className="system-label label-two"><i />DATA</div><div className="system-label label-three"><i />PRODUCT</div><div className="system-label label-four"><i />CONTROL</div></div>
      <div className="hero-index"><span>01</span><i /><span>SCROLL TO EXPLORE</span></div>
    </section>
    <div className="capability-strip" aria-label="Core capabilities"><div><span>AGENTIC AI</span><i>✦</i><span>RAG SYSTEMS</span><i>✦</i><span>MACHINE LEARNING</span><i>✦</i><span>COMPUTER VISION</span><i>✦</i><span>FULL-STACK AI</span><i>✦</i><span>AGENTIC AI</span><i>✦</i><span>RAG SYSTEMS</span></div></div>

    <section className="manifesto section shell"><p className="section-index">/ APPROACH</p><div><p className="manifesto-lead">A promising model is only the beginning.</p><p className="manifesto-main">I design the <em>system around the intelligence</em>—the data, workflow, interface, evaluation, controls, and product decisions that make AI useful beyond the demo.</p><Link className="text-link" href="/about">How I work <Arrow /></Link></div></section>

    <section className="evidence-section shell" aria-labelledby="evidence-title"><div className="evidence-intro"><p className="kicker"><span>Engineering evidence</span></p><h2 id="evidence-title">Measured where it matters.</h2><p>Research and implementation signals from selected projects—shown with context, never inflated into business claims.</p></div><div className="evidence-grid">{engineeringMetrics.map((metric) => <article key={metric.label}><strong>{metric.value}</strong><span>{metric.label}</span><p>{metric.context}</p></article>)}</div><small>* Research evaluation metric; NeuroGlioma AI is not a medical diagnosis.</small></section>

    <section className="section work-section shell"><SectionHeading eyebrow="Selected work" title="Systems with a reason to exist." action={<Link className="text-link desktop-action" href="/work">View all work <Arrow /></Link>} /><div className="featured-work">{caseStudies.slice(0, 3).map((project, index) => <Link className="project-card" href={`/work/${project.slug}`} key={project.slug}><ProjectVisual variant={project.accent} /><div className="project-meta"><span>0{index + 1}</span><p>{project.eyebrow}</p><Arrow diagonal /></div><h3>{project.title}</h3><p className="project-summary">{project.summary}</p><div className="tags">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></Link>)}</div></section>

    <section className="section services-preview"><div className="shell"><SectionHeading eyebrow="Capabilities" title="From idea to intelligent product." /><div className="service-list">{services.map((service) => <Link href={`/services/${service.slug}`} className="service-row" key={service.slug}><span>{service.number}</span><h3>{service.title}</h3><p>{service.short}</p><Arrow diagonal /></Link>)}</div></div></section>

    <section className="section founder-section shell"><div className="founder-grid"><div className="founder-copy"><p className="kicker"><span>Founder’s build log</span></p><h2>Building the control room for an AI workforce.</h2><p>As Co-Founder of AgentHive, I’m working on a platform where companies can create, configure, and govern tool-connected AI agents—with human approvals, scoped memory, permissions, budgets, and visible task execution.</p><div className="build-status"><span><i /> Current stage</span><strong>Controlled POC → Multi-tenant MVP</strong></div><Link className="button button-primary" href="/work/agenthive">Explore the case study <Arrow /></Link></div><div className="control-room" aria-hidden="true"><div className="room-header"><span><i /> AGENTHIVE / CONTROL ROOM</span><b>POC</b></div><div className="room-stats"><div><small>ACTIVE FLOW</small><strong>Sales follow-up</strong></div><div><small>TOOLS</small><strong>03 simulated</strong></div></div><div className="room-timeline"><span className="done"><i>✓</i><b>01</b>Understand task</span><span className="done"><i>✓</i><b>02</b>Retrieve context</span><span className="active"><i>!</i><b>03</b>Human approval<em>Waiting</em></span><span><i>·</i><b>04</b>Generate report</span></div><div className="room-footer"><span>Budget protected</span><span>Memory scoped</span><span>Audit ready</span></div></div></div></section>

    <section className="section process-section"><div className="shell"><SectionHeading eyebrow="Working model" title="Clarity before complexity." /><div className="process-grid">{[["01", "Frame", "Define the user, decision, workflow, risk, and useful outcome before selecting the AI approach."], ["02", "Prototype", "Build the smallest end-to-end path that tests the riskiest product and technical assumptions."], ["03", "Evaluate", "Measure retrieval, model behavior, edge cases, UX, and failure handling with representative inputs."], ["04", "Engineer", "Strengthen the data, APIs, state, controls, observability, and interface required for dependable use."]].map(([n, title, copy]) => <article key={n}><span>{n}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>

    <section className="section insights-section shell"><SectionHeading eyebrow="Weekly blog" title="What I’m learning while building." action={<Link className="text-link desktop-action" href="/blog">Visit the blog <Arrow /></Link>} /><div className="insight-grid">{insights.map((post, index) => <Link href={`/blog/${post.slug}`} className={`insight-card insight-${index + 1}`} key={post.slug}><div><span>{post.category}</span><Arrow diagonal /></div><h3>{post.title}</h3><p>{post.description}</p><small>{post.date} · {post.readingTime}</small></Link>)}</div><Link className="mobile-blog-link button button-ghost" href="/blog">Browse all articles <Arrow /></Link></section>

    <section className="section audit-cta shell"><div className="audit-panel"><div><p className="kicker"><span>AI Opportunity Map</span></p><h2>Where could AI remove friction from your work?</h2></div><div><p>Describe one repetitive, knowledge-heavy, or decision-heavy workflow. I’ll help you frame what should be automated, what should stay human, and what a useful first version could look like.</p><Link className="button button-dark" href="/contact?intent=audit">Map my opportunity <Arrow /></Link></div></div></section>
  </main><Footer /></>;
}
